### ISSUE TITLE
Overriding save_formset?

### ISSUE THREAD

**Issue by asandhu3** [theatlantic/django-nested-admin#102]
I'm trying to override the save_formset function to allow for setting a user ID upon save of the model. It doesn't seem to be even entering the function. Apologies if I'm missing something but I don't see this documented anywhere.

```python
class MedicationLogItemRowInline(nested_admin.NestedTabularInline):
    model = MedicationLogItemRow
    extra = 1

class MedicationLogItemInline(nested_admin.NestedTabularInline):
    model = MedicationLogItem
    inlines = [
        MedicationLogItemRowInline,
    ]
    extra = 1

    def save_formset(self, request, form, formset, change):
        formset.save()
        for f in formset.forms:
            obj = f.instance
            if obj.pk:
                if 'field_1' in form.changed_data:
                    obj.field_updated_by = request.user        

class MedicationLogAdmin(nested_admin.NestedModelAdmin):
    inlines = [
        MedicationLogItemInline,
    ]
```

**Comment by fdintino** [comment]
I believe that `save_formset()` only gets called on the `ModelAdmin` class, not on inlines. However, django-nested-admin flattens out all formsets on save, so you should be able to access them in `MedicationLogAdmin.save_related` or `MedicationLogAdmin.save_formset`
