### ISSUE TITLE
Browser memory is bloated when adding more than 2 nested inlines

### ISSUE THREAD

**Issue by MiltosD** [theatlantic/django-nested-admin#106]
Hello, 
Has anyone experienced that the browser becomes very slow when adding multiple inline formsets? This only happens only when they are dynamically added and I was wondering if this is a django (I'm using v2.0) or nested-admin issue.

Thanks

**Comment by fdintino** [comment]
It might help to use the chrome web inspector to see what's going on. There shouldn't be any more slowness than you would see with adding a non-nested inline. That said, the javascript code could probably stand to be profiled and sped up some. But in your case I would first verify that there isn't some other extension or widget that's responsible.
