### ISSUE TITLE
Create another [model_name] hyperlink not working

### ISSUE THREAD

**Issue by samroberts707** [theatlantic/django-nested-admin#107]
I have just imported this app in to my project for nesting which appears it should work perfectly for what I need.

Unfortunately though the "Add another [model_name]" text doesn't work when creating more objects. When pressing the hyperlink nothing happens. In the console log there is a jquery error, see accompanying screenshot.

I've made sure that I collected all static files and I'm not getting any 404's when the page loads so I don't believe anything is missing.
![screen shot 2018-08-13 at 17 02 50](https://user-images.githubusercontent.com/7763311/44043477-de84c88a-9f1a-11e8-9345-980a42bb1028.png)

**Comment by fdintino** [comment]
This should be fixed in the latest release (created just this morning) 3.1.1

**Comment by samroberts707** [comment]
Thank you for the quick response, I should probably have checked for a new version but seeing as I installed the package this morning it slipped my mind. I must have just missed the new release.
