### ISSUE TITLE
Support NestedTabularInline (feature request)

### ISSUE THREAD

**Issue by olivierdalang** [theatlantic/django-nested-admin#11]
Hi !

It would be awesome if it was possible to display the nested inlines using the tabular view as well. I tried to have a look at the code, but it's a bit over my competences :/

Bests,

Olivier

**Comment by jokerejoker** [comment]
+1

**Comment by TheDimLebowski** [comment]
+1

**Comment by fdintino** [comment]
I was concerned that getting drag-and-drop to work would be tricky with a tabular inline, but it looks like grappelli manages it. But would it be alright if the first iteration didn't support drag and drop?

**Comment by olivierdalang** [comment]
@fdintino Currently, as a workaround, I use regular TabularInline as inline for my NestedAdmins. Surprisingly, it's almost usable : when creating a new object, I just need to hit "save & continue" once, then I can use regular inlines including drag&drop with grappelli. The inlines don't work (you can't add any inline object) when adding a new object though, which is a bit annoying.

So, of course, a first iteration without drag&drop would already be great, but it would be even better if it is supported ;)

Thanks for the great work ! I'd love to help on this, but I'm not familiar enough with Django to understand how to...

**Comment by LaurensBER** [comment]
Considering that this is the most active and well maintained nested inlines solutions on github I think it would make a very good addition.

The other solutions do implement nested tabular inlines, it might be worth taking a look at how they solved it;

- https://github.com/Soaa-/django-nested-inlines
- https://github.com/BertrandBordage/django-super-inlines
- https://github.com/s-block/django-nested-inline

**Comment by jokerejoker** [comment]
@fdintino No drag'n'drop support will be more than okay for me. At least it is closer to the goal than the current state of code and for people like me that is not using grappelli or drag'n'drop where I need the nested admin it will be perfect.

Some one will probably open a request for drag'n'drop support later on ;)

**Comment by fdintino** [comment]
Getting this to work was a bit more involved than I anticipated. Nevertheless, it should now work, with or without grappelli, and optionally with drag-and-drop sorting. Some of the css selectors changed in the process, so on the off chance that you are styling on top of django-nested-admin, you may want to hold off on updating until you've had a chance to update your css or javascript.

I'm going to close this ticket, as all selenium unit tests that passed for stacked inlines are now passing for tabular inlines across all supported environments. If anyone encounters bugs in trying to implement `NestedTabularInline`, please feel free to open a new ticket.

Thanks everyone for the encouragement.
