### ISSUE TITLE
FileFields in deeply nested inlines broken in Django 2.1

### ISSUE THREAD

**Issue by alito** [theatlantic/django-nested-admin#111]
Image uploading in the first inline level works fine, but in the second level it gets ignored. Nothing fails and the rest of the formsets get saved fine, but the file upload doesn't happen, the file is not in the server, and the corresponding entry in the database is not stored.

BTW, this is using Django 2.1 and code like the following:

```
class CatImageInline(nested_admin.NestedStackedInline):
    model = ourmodels.CatImage
    extra = 1

class CatInline(nested_admin.NestedStackedInline):
    model = ourmodels.Cat
    extra = 2

    inlines = [
        CatImageInline,
    ]


@admin.register(ourmodels.FeralCatSurvey)
class FeralCatSurveyAdmin(nested_admin.NestedModelAdmin):
     inlines = [
        CatInline
    ] 

```

**Comment by fdintino** [comment]
For the model with the file field, is that the only field on the form? Or are there other fields in the same inline? If, for instance, there is a charfield, try filling out that field _and_ uploading a file at the same time, to see if that works. If the adjacent charfield saves but the file doesn't upload, that will suggest one issue. If they both save, however, then I have a theory for why that might be (and so, how I would fix it).

**Comment by alito** [comment]
Ok, tracked it down a bit. The issue is that Django admin doesn't set 'multipart/form-data' on the HTML form if none of the fields it knows about in the formsets it knows about need multipart. The relevant code bit is in contrib/admin/options.py in render_change_form.
I don't know what the proper fix is, but a simple workaround that seems to work is to set a form on the admin object, where the form just overrides is_multipart. eg:
```
class FeralCatSurveyForm(forms.ModelForm):
    def is_multipart(self):
       return True

    class Meta:
        ....
```

**Comment by fdintino** [comment]
Oh interesting. Looks like this logic got added in Django 2.1. I'll see what I can do for a general fix.

**Comment by jayantamadhav** [comment]
I have the same problem, so how do I fix it?
I'm running Django-2.2

**Comment by agalazis** [comment]
I think you need to reoppen, for I don't see it working I had to set in my parent form is_multipart  method that returns true to make it work  I could only see first level of inlines being checked from debugger

**Comment by agalazis** [comment]
also noticed that same goes with obj given to get_read_only_fields e.t.c. it is just first level inline object
