### ISSUE TITLE
How to show help_text of an field in tabular inline

### ISSUE THREAD

**Issue by skinderis** [theatlantic/django-nested-admin#119]
Hey,

I have a small problem that I cant see the help_text of a field in nested tabular inline mode. How I can do so it will show.

You can see that there is no help_text:
![image](https://user-images.githubusercontent.com/24273695/51398936-686e4680-1b4d-11e9-83d0-88762ac72f82.png)
I need it to show help_text value like this:
![image](https://user-images.githubusercontent.com/24273695/51399006-93f13100-1b4d-11e9-9aa8-66186546f1ce.png)

Thanks.

**Comment by fdintino** [comment]
There is the (?) icon which, on hover, shows the help text. This isn't a feature of django-nested-admin, it's just copying the way the regular django admin displays help text in tabular inlines.

**Comment by TrungKien1230** [comment]
@fdintino  When i click on the icon ? I see nothing

**Comment by TrungKien1230** [comment]
@skinderis  Did you find how to fix it ? I have the same problem

**Comment by fdintino** [comment]
It shows the help text on hover, not click. However, it's not a design I can change: that's just the way it looks in the django admin for tabular inlines.
