### ISSUE TITLE
M2M field on double nested-inline causes error

### ISSUE THREAD

**Issue by matt-dalton** [theatlantic/django-nested-admin#120]
I've got a (possible ridiculous) situation where I have two nested inlines, then a m2m field on the inner-most inline. Here is my `admin.py`:

    class ArticleNested2Inline(nested_admin.NestedStackedInline, SortableInlineAdminMixin):
       model = ArticleNested2
       extra = 0

    class ArticleNestedInline(nested_admin.NestedStackedInline):
       model = ArticleNested
       extra = 0
       inlines = [ArticleNestedInline]

    @admin.register(Pack)
    class ArticleAdmin(nested_admin.NestedModelAdmin):
        model = Article

Then my `ArticleNested2` model has a many-to-many field called `products`.

Then if I try and add a new `ArticleNested2` in Django admin I get:

`ValueError: "<ArticleNested2: >" needs to have a value for field "id" before this many-to-many relationship can be used.`

Is there some method I can override to save my ArticleNested2 object before it tries to associate it with a product?

**Comment by fdintino** [comment]
I think the issue here is that you aren't using many-to-many models and inlines correctly. The django docs have information about [how to use inlines with M2M relationships](https://docs.djangoproject.com/en/1.11/ref/contrib/admin/#working-with-many-to-many-models). The examples there would be the same for django-nested-admin (except that you can nest the inlines deeper than one level).

**Comment by matt-dalton** [comment]
Ah sorry, maybe I wasn't clear.

The m2m field I am talking about is a field on `ArticleNested2`. It links through to `products`. I haven't created an extra inline for it, but `ArticleNested2` doesn't save before it tries to set up the m2m relation.

**Comment by matt-dalton** [comment]
Ah eventually found out the fix for this - for the benefit of anyone reading:

My problem wasn't with the nested admin lib. I had a `clean` function on _the model_ where was doing a check for my M2M field `self.products`. This is not defined in the model's clean function, and this error was confusingly bubbling up to the nested admin lib.

I recreated the model's clean function in the form for the inline form, and it worked 👍

Thanks for helping me out!

**Comment by fdintino** [comment]
Glad you got it sorted out!
