### ISSUE TITLE
Can't use the tag extrastyles in your own template

### ISSUE THREAD

**Issue by jonathan-s** [theatlantic/django-nested-admin#124]
If you're using your own template in admin and using `{% block extrastyles %}` to add some extra styles and overwrite django-nested-admin styles that will fail because the styling for extrastyles comes before the nested admin styles. 

Ideally the styling from nested admin should come before that styling block.

**Comment by fdintino** [comment]
We don't define a `{% block extrastyle %}` in any of our templates, so if it's not showing up for you in the correct place in relation to form media, that would be an issue with django itself (or grappelli, or whatever skin you might be using). I notice that you wrote `{% block extrastyles %}`, but the block is actually `extrastyle` (singular)—could that be the issue?

**Comment by jonathan-s** [comment]
Hmm, I double-check regarding the typo. That is not the issue. I also checked the django code. https://github.com/django/django/blob/master/django/contrib/admin/templates/admin/change_form.html#L4-L9

Where it looks like `{{ media }}` is placed before extrastyle. Nonetheless extrastyle shows up before the nested inline styles css link tag... 

Might be an issue with django somehow, feel free to close this if you think it is out of scope.

**Comment by fdintino** [comment]
Okay. I think I'll close this, only because whatever is changing the relative order of `{{ media }}` and `{% block extrastyles %}` would have to be outside of django-nested-admin.
