### ISSUE TITLE
Prepopulate fields from FK field in nested situation

### ISSUE THREAD

**Issue by jonathan-s** [theatlantic/django-nested-admin#126]
Let's say that we've got a FK field and that we need to copy some of these values from the FK parent. When you click add another there is no easy way of making this happen, all the fields will turn up blank. 

I think there should be a built-in way of defining what fields you'd like to pre-fill and when you click `add another` those fields should be prefilled from the FK parent.

**Comment by fdintino** [comment]
Is this already a feature of django or django-grappelli? It sounds like your use-case is a bit too specific to turn into a general-purpose feature. You can use jquery to hook into an event when a formset is added; we use the same events as django so you can use [their docs on the topic](https://docs.djangoproject.com/en/1.11/ref/contrib/admin/javascript/) as a guide.

**Comment by jonathan-s** [comment]
You're right, it's probably best to solve this within the app itself. Thanks for the heads-up!
