### ISSUE TITLE
Option to repeat headers when using inline

### ISSUE THREAD

**Issue by jonathan-s** [theatlantic/django-nested-admin#132]
When you're using a tabularinline and there are several items it will look something like this. 

```
- Header
- Item
    - inline
    - inline
    - inline
- Item
    - inline
    - inline
    - inline
- Item
    - inline
    - inline
```

The issue is that when you scroll down you won't be able to see the header any longer for the last item if there are many. So readability becomes an issue. I would suggest that there is at least an option to repeat the header for each item, or that this becomes the default option. This makes it a lot more readable. 

Let me know what you think.

**Comment by fdintino** [comment]
You're welcome to propose this to the grappelli project, but I don't think we ought to be introducing features in a way that behave differently from how the django admin works without django-nested-admin.
