### ISSUE TITLE
Drop support for python 3.4

### ISSUE THREAD

**Issue by jonathan-s** [theatlantic/django-nested-admin#134]
Python 3.4 won't be supported past March 2019. It has reached end of life - see https://www.python.org/dev/peps/pep-0429/

So it's probably prudent to drop this in travis. Tangentially related to #133 as that's where I discovered it.

**Comment by fdintino** [comment]
python 3.4 support will effectively be dropped when django 1.8 support is dropped. That will probably happen with the next major support release.
