### ISSUE TITLE
No "add" button for `NestedTabularInline` (grappelli)

### ISSUE THREAD

**Issue by dustinmichels** [theatlantic/django-nested-admin#136]
Greetings,

Thank you for sharing this excellent, very useful library.

I am attempting to use the `NestedTabularInline` inline, with grappelli.

If I use `NestedStackedInline`, a foreign key field on the Inline model comes with a `+` button to create a new instance of the model.

![Screen Shot 2019-04-09 at 2 54 50 PM](https://user-images.githubusercontent.com/16504363/55834714-c7ea4b80-5ad7-11e9-8e93-ff2013ff5b33.png)

If I use `NestedTabularInline` inline however, like I want to, the "add" button disappears. I only see the "edit" arrow.

![Screen Shot 2019-04-09 at 2 56 13 PM](https://user-images.githubusercontent.com/16504363/55834862-0bdd5080-5ad8-11e9-846f-917a72bb0ed2.png)

Thanks for your help.

**Comment by fdintino** [comment]
It looks like this is caused by sehmaschine/django-grappelli#884—I see the same issue with regular grappelli `TabularInline`, but I can adjust the stylesheets to fix the issue for users of django-nested-admin.

**Comment by fdintino** [comment]
Can you pip install the fix-grappelli-tabular-inline-styles branch locally to see if everything is styled correctly?

```
pip install -e git+git@github.com:theatlantic/django-nested-admin.git@fix-grappelli-tabular-inline-styles#egg=django-nested-admin
```

**Comment by dustinmichels** [comment]
Thank you for your responsiveness! I'm getting an access error:

```
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by fdintino** [comment]
Try this then:

```
pip install -e git+https://github.com/theatlantic/django-nested-admin.git@fix-grappelli-tabular-inline-styles#egg=django-nested-admin
```

**Comment by dustinmichels** [comment]
That looks excellent! Thank you!
