### ISSUE TITLE
Adding Add Another record button though Ajax doesnt reload plugin

### ISSUE THREAD

**Issue by jas-odoo** [theatlantic/django-nested-admin#143]
Adding Add Another record button though Ajax doesn't reload the plugin.

I try to figure out in nested_admin.js, but it is returning nothing, so we can init plugin again.

**Comment by fdintino** [comment]
What do you mean "through Ajax"? Is that referring to another django admin extension?

**Comment by fdintino** [comment]
Closing because of lack of feedback. If you can provide more details feel free to reopen.
