### ISSUE TITLE
Be able to disable server-datajs (server_data_js view)

### ISSUE THREAD

**Issue by manelclos** [theatlantic/django-nested-admin#155]
Hi!

We don't use Grappeli, nor we are using staticfiles, so on every page load we have a request that could be avoided and that is a bit annoying because it produces a 500 error (because of our configuration and your use of staticfiles here: https://github.com/theatlantic/django-nested-admin/blob/master/nested_admin/views.py#L36). We have mapped the url to an empty endpoint, but it would be better to avoid the request.

Could it be possible to add a DJN_DISABLE_SERVER_DATA_JS variable that defaults to False so we can avoid that url request?

Thanks!

**Comment by fdintino** [comment]
Sorry it's taken me this long to respond—this issue somehow escaped my notice when it was first posted. I wouldn't have any issue with introducing this setting. If you opened a PR it would probably get merged in sooner than if it waited until I have some free time to do it myself.
