### ISSUE TITLE
nested inline saving error

### ISSUE THREAD

**Issue by bjornpoort** [theatlantic/django-nested-admin#16]
when this package is used with grappelli 2.7.2, django 1.8.3, python 3.5, it is not possible to save a nested inline. instead it overrides the value of the field with (supposedly) the id number. see snapshot below;

![schermafbeelding 2015-11-09 om 20 09 59](https://cloud.githubusercontent.com/assets/14273799/11043585/bb0333be-871d-11e5-947b-bcbe7f31ac14.png)

anyone else noticed this issue?

**Comment by fdintino** [comment]
Is there any chance you have something like:

```python
sortable_field_name = "position"
```

on your `InlineModelAdmin` class?

**Comment by bjornpoort** [comment]
thank you very much sir. that did the trick!
