### ISSUE TITLE
Hello, are there someone who use pycharm and cannot use django-nested-admin ? "cannot find reference NestedTabularInline in __init__.py ?

### ISSUE THREAD

**Issue by TrungKien1230** [theatlantic/django-nested-admin#162]

**Comment by pasevin** [comment]
Yes, I have this issue. Have you found a fix?

**Comment by TrungKien1230** [comment]
Yes, you can use it as tutorials, then click on it and do Alt+Enter, then choose ignore, it works for me

**Comment by pasevin** [comment]
Hmm yeah, this is not a good solution, because then pycharm just can't find overridden methods etc.
