### ISSUE TITLE
"Add Another <Model>' links not being generated, showing only 'javascript://' links 

### ISSUE THREAD

**Issue by euanmacinnes** [theatlantic/django-nested-admin#163]
Hi,
    I'm using the django admin behind a reverse proxy, which uses the URL sub-folder path /pipeline/<apps> to go to the individual Django apps and admin (which is in /pipeline/admin'),

so I've set up the rules as follows:

urlpatterns = [
    path('pipeline/rules/', include('rules.urls')),
    path('pipeline/materials/', include('materials.urls')),
    path('pipeline/admin/', admin.site.urls),       
    path('pipeline/nested_admin/', include('nested_admin.urls')),
]

EDIT:
  I also tried this with:

urlpatterns = [
    path('pipeline/rules/', include('rules.urls')),
    path('pipeline/materials/', include('materials.urls')),
    path('pipeline/admin/', admin.site.urls),       
    url(r'^nested_admin/', include('nested_admin.urls')),
]

To no avail.

The nested inlines all appear in Django admin, and Saving the data all work fine, but the links to 'Add Another <Model>' all just show 'javascript://' in the URL in the browser, rather than the expected URLs.

This has to go through a subfolder for many security reasons and multi-homed applications etc.. so I've no option to change this to a port or a different main address.

Any help given is greatly appreciated.

**Comment by fdintino** [comment]
The 'Add Another' button isn't a link—it doesn't take you to a different page—it triggers a registered click handler in javascript that adds a new inline. The fact that the link says `javascript://` in the browser shouldn't cause any issues with whatever admin urls you're using.

**Comment by euanmacinnes** [comment]
Hi Frankie,
        Ah, the links aren't responding to clicks though. Save / edit works
just fine, I just can't add any new records. Any thoughts as to the cause?
(Normal django admin works fine, it's just the nested ones that don't
respond. Chrome browser)

Cheers,

Euan.

**Comment by fdintino** [comment]
Are there any errors in the Web Developer console?

**Comment by selected-pixel-jameson** [comment]
I'm seeing the same issue. No there are no errors in the console. Running Django 2.1.

**Comment by selected-pixel-jameson** [comment]
@euanmacinnes Are you by chance storing files to S3 and / or using the ManifestFilesMixin or S3Boto3Storage?

**Comment by fdintino** [comment]
@selected-pixel-jameson I see the issue. You need your admin class to extend `nested_admin.NestedModelAdmin`, _not_ `admin.ModelAdmin`. I suspect that if you change that, it will work.

**Comment by euanmacinnes** [comment]
The problem in the end was the Static files, as they didn't get installed into the published location that went through the reverse proxy. A quick file copy over later got it working again.
