### ISSUE TITLE
Control nested display to not use popups

### ISSUE THREAD

**Issue by gnujosh** [theatlantic/django-nested-admin#169]
I'm fairly new to Django and I have a simple model that I'm having trouble controlling the admin interface on.  I want a user to be able to edit the content on a page.  To support that, I have a PageContent model, which can have multiple PageSection models, each of which can have multiple PageParagraph models.  Since I have different types of pages that each can include a PageContent, I used a OneToOneField for any page model type that will contain a PageContent.

#### models.py
```
class PageContent(models.Model):
    pass

class PageSection(models.Model):
    heading = models.CharField(max_length=100)
    content = models.ForeignKey(PageContent, on_delete=models.CASCADE)

class PageParagraph(models.Model):
    paragraph = models.TextField()
    section = models.ForeignKey(PageSection, on_delete=models.CASCADE)

class PageTypeOne(models.Model):
    ...
    content = models.OneToOneField(PageContent, on_delete=models.CASCADE)
```
#### admin.py
```
class PageParagraphInline(nested_admin.NestedStackedInline):
    model = PageParagraph

class PageSectionInline(nested_admin.NestedStackedInline):
    model = PageSection
    inlines = [PageParagraphInline]

class PageContentInline(nested_admin.NestedStackedInline):
    model = PageContent
    inlines = [PageSectionInline]

class PageTypeOneAdmin(nested_admin.NestedModelAdmin):
    pass

admin.site.register(PageTypeOne, PageTypeOneAdmin)
```
What I would like to get is something like [this](https://www.frankiedintino.com/static/misc/nested-admin-issue-135.png), where you can see the editable fields for each nested layer from the top level ModelAdmin.

Instead, I get a dropdown box and a + symbol that pops up the admin interface for the PageContent model in a separate window.
![screenshot](https://user-images.githubusercontent.com/24919920/78165245-0976b380-7419-11ea-99eb-5916726f5963.png)

Is there a way to force the nested models to show up in the same page rather than on a popup?

Thanks!

**Comment by gnujosh** [comment]
Additionally, I noticed if I don't make and register a PageContentAdmin, I don't even get the + symbol or popup option.

### admin.py
```
class PageContentAdmin(nested_admin.NestedModelAdmin):
    inlines = [PageSectionInline]

admin.site.register(PageContent, PageContentAdmin)
```

**Comment by fdintino** [comment]
The issue here is that you need to setup your inlines so that the model with the foreign key is setup as an inline admin on the foreign key's related model. So, since `PageTypeOne` has a `ForeignKey` to `PageContent`, it would need to be included in `PageContentAdmin.inlines` to work the way you want. The end result would look something like this:

```python
class PageParagraphInline(nested_admin.NestedStackedInline):
    model = PageParagraph

class PageSectionInline(nested_admin.NestedStackedInline):
    model = PageSection
    inlines = [PageParagraphInline]

class PageTypeOneInline(nested_admin.NestedStackedInline):
    model = PageTypeOne

class PageContentAdmin(nested_admin.NestedModelAdmin):
    model = PageContent
    inlines = [PageSectionInline, PageTypeOneInline]

admin.site.register(PageContent, PageContentAdmin)
```
