### ISSUE TITLE
SSL Internal server error

### ISSUE THREAD

**Issue by mandywil** [theatlantic/django-nested-admin#17]
We're using django-nested-admin and it seems to work fine except on our non-SSL site; when we try it there, we get the following error.  We have configured the settings.py and urls.py as you've described here.  The wsgi.py has the same permissions and content on both our ssl and non-ssl site.  Do you have any ideas?  Thanks!  PS, we started out using nested-inlines, but we had the same problem there.

Target WSGI script '/apps/staging/wisdmepid/django_version/django_version/wsgi.py' cannot be loaded as Python module.

[Wed Nov 18 11:14:29.322753 2015] [:error] [pid 14068] [remote 128.173.38.156:104] mod_wsgi (pid=14068): Target WSGI script '/apps/staging/wisdmepid/django_version/django_version/wsgi.py' cannot be loaded as Python module.
[Wed Nov 18 11:14:29.322819 2015] [:error] [pid 14068] [remote 128.173.38.156:104] mod_wsgi (pid=14068): Exception occurred processing WSGI script '/apps/staging/wisdmepid/django_version/django_version/wsgi.py'.
[Wed Nov 18 11:14:29.322851 2015] [:error] [pid 14068] [remote 128.173.38.156:104] Traceback (most recent call last):
[Wed Nov 18 11:14:29.322873 2015] [:error] [pid 14068] [remote 128.173.38.156:104]   File "/apps/staging/wisdmepid/django_version/django_version/wsgi.py", line 18, in <module>
[Wed Nov 18 11:14:29.322955 2015] [:error] [pid 14068] [remote 128.173.38.156:104]     application = get_wsgi_application()
[Wed Nov 18 11:14:29.322970 2015] [:error] [pid 14068] [remote 128.173.38.156:104]   File "/apps/staging/wisdmepid/django_version/env/lib/python2.7/site-packages/django/core/wsgi.py", line 14, in get_wsgi_application
[Wed Nov 18 11:14:29.323024 2015] [:error] [pid 14068] [remote 128.173.38.156:104]     django.setup()
[Wed Nov 18 11:14:29.323034 2015] [:error] [pid 14068] [remote 128.173.38.156:104]   File "/apps/staging/wisdmepid/django_version/env/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
[Wed Nov 18 11:14:29.323096 2015] [:error] [pid 14068] [remote 128.173.38.156:104]     apps.populate(settings.INSTALLED_APPS)
[Wed Nov 18 11:14:29.323107 2015] [:error] [pid 14068] [remote 128.173.38.156:104]   File "/apps/staging/wisdmepid/django_version/env/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
[Wed Nov 18 11:14:29.323251 2015] [:error] [pid 14068] [remote 128.173.38.156:104]     app_config = AppConfig.create(entry)
[Wed Nov 18 11:14:29.323266 2015] [:error] [pid 14068] [remote 128.173.38.156:104]   File "/apps/staging/wisdmepid/django_version/env/lib/python2.7/site-packages/django/apps/config.py", line 86, in create
[Wed Nov 18 11:14:29.323374 2015] [:error] [pid 14068] [remote 128.173.38.156:104]     module = import_module(entry)
[Wed Nov 18 11:14:29.323393 2015] [:error] [pid 14068] [remote 128.173.38.156:104]   File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
[Wed Nov 18 11:14:29.323448 2015] [:error] [pid 14068] [remote 128.173.38.156:104]     __import__(name)
[Wed Nov 18 11:14:29.323471 2015] [:error] [pid 14068] [remote 128.173.38.156:104] ImportError: No module named nested_admin

**Comment by fdintino** [comment]
This sounds like an issue with how you've configured mod_wsgi, and is not specific to this library.
