### ISSUE TITLE
Issue with Grappelli 2.14.1

### ISSUE THREAD

**Issue by pasevin** [theatlantic/django-nested-admin#178]
There is an issue created in Grappelli repo: https://github.com/sehmaschine/django-grappelli/issues/941

And I'm experiencing exactly the same.

But I think this is related to ```django-nested-admin``` specifically rather than Grappelli.
Because once I replace ```NestedTabularInline``` with Django native ```TabularInline``` it works with no errors.

Directly related to this change: https://github.com/sehmaschine/django-grappelli/commit/57fc5bdf959a9b173664071982502b44fa9b8404

**Comment by pasevin** [comment]
Replacing:
```module.exports = window.django.jQuery;```

To:
```module.exports = window.jQuery;```

...fixes this, although I don't know why and if it's safe.

**Comment by pasevin** [comment]
Another problem related to this issue is that autocomplete is not getting initialized once we add new inline.

This is wat has been added on the Grappelli side(https://github.com/sehmaschine/django-grappelli/commit/57fc5bdf959a9b173664071982502b44fa9b8404):
```javascript
// select2: we need to use the django namespace here
django.jQuery(document).trigger('formset:added', [django.jQuery(form), options.prefix]);
```

So as I can see you override Grappelli's ```addButtonHandler``` with ```add(spliceIndex, ctype) {...``` we should probably add the same line to jquery.djangoformset.js:


```javascript
if (grappelli) {
    grappelli.reinitDateTimeFields($form);
    // select2: we need to use the django namespace here
    django.jQuery(document).trigger('formset:added', [django.jQuery(form), options.prefix]);
}
```

**Comment by pasevin** [comment]
I didn't have enough time to dive deeper into both ```Grappelli``` and ```django-nested-admin```, but if you think this is a good solution, I can create a PR for this.

**Comment by fdintino** [comment]
I'm pretty sure I know what the issue is here. I'll verify with the tests and then push out a fix.
