### ISSUE TITLE
Change url to re_path in nested_admin/urls.py

### ISSUE THREAD

**Issue by AlekseiKhatkevich** [theatlantic/django-nested-admin#195]
Hi

You perhaps need to change path to re_path here

```
urlpatterns = [
    url(r'^server-data\.js$', nested_admin.views.server_data_js,
        name="nesting_server_data"),
]
```
as url here causes  deprecation warning in Django 3.1
```

  /app/venv/lib/python3.9/site-packages/nested_admin/urls.py:8: RemovedInDjango40Warning: django.conf.urls.url() is deprecated in favor of django.urls.re_path().
    url(r'^server-data\.js$', nested_admin.views.server_data_js,
```

**Comment by TimurKhan** [comment]
@AlekseiKhatkevich I couldn't get this joy running on Django 3.1 at all. The last thing I gave up on was the message:

> File "D:\Envs\django\lib\site-packages\nested_admin\__init__.py", line 70, in __getattr__
>     return ModuleType.__getattribute__(self, name)
> AttributeError: module 'nested_admin' has no attribute 'views'
