### ISSUE TITLE
support show_change_link added in Django 1.8

### ISSUE THREAD

**Issue by jlemaes** [theatlantic/django-nested-admin#22]
Hi,

It would be nice to support the [show_change_link](https://docs.djangoproject.com/en/1.8/ref/contrib/admin/#django.contrib.admin.InlineModelAdmin.show_change_link) in the nested admin to provide a link to the object change form in the admin.

Jasper

**Comment by fdintino** [comment]
Yes, that's a good idea. Should be relatively easy to do as well. I won't be able to do it until next week at the earliest though.

**Comment by fdintino** [comment]
Support for `show_change_link` was added in the 3.0 release.

**Comment by mc8ain1** [comment]
I'm using django==1.9.11 and django-nested-admin==3.0.12, when `show_change_link` is set to `True` **AND** `sortable_field_name` set to a field, the change link disappears.

**Comment by ryanprater** [comment]
@fdintino can confirm what @ubeerli says. Both of those options enabled result in the change link disappearing. Not using Grappelli.
