### ISSUE TITLE
Weird behavior with `max_num` and nested inlines

### ISSUE THREAD

**Issue by NeilujD** [theatlantic/django-nested-admin#230]
I am using `django-nested-admin` in order to recursively create relations with the same model (like a parent/child relationship).
So I have three levels of nested inlines: `Level1`, `Level2` and `Level3`

`Level2` and `Level3` have is not limited with the `max_num` option but `Level1` is limited with 2 as its `max_num`'s value.
It means that I can have as many `Level3` nested in a `Level2` and `Level2` in a `Level1` as I want.

But when I reach the maximum number of `Level1`, all the links to add a nested objects are hidden, included the one permitting to add `Level2` or `Level3` objects. Thus even if I can add a second Level1, I can add nested objects in itself or even in other Level objects that were already existing.

* Image 1 is before reaching the maximum number
![Image 1](https://user-images.githubusercontent.com/1380523/199475434-b69b9056-1881-4da0-8f61-a1cf4147624d.png)

* Image 2 is when the maximum number is reached
![Image 2](https://user-images.githubusercontent.com/1380523/199475447-8c1b3629-023d-4b59-a74d-35a0b19ec026.png)

I am using:
* Django 3.2.15
* django-nested-admin 3.4

Could you help me on that please ?
Did I miss something or is it an issue ?

**Comment by fdintino** [comment]
Oh, I see the bug here. I'll try to get a fix out this week, though it may not happen until next week. Thanks for the report!
