### ISSUE TITLE
pypi update

### ISSUE THREAD

**Issue by VincentVW** [theatlantic/django-nested-admin#24]
Could Pypi be updated to the latest release?

https://pypi.python.org/pypi/django-nested-admin

The current release there (2.1.8) is incompatible with the latest Django releases (1.9.x) while 2.1.11 is.

Thanks for the package btw! The first to support all our use cases (3th we tried, ugh.. ).

**Comment by fdintino** [comment]
Done. Glad the package is useful for you!

**Comment by VincentVW** [comment]
@fdintino Thanks!
