### ISSUE TITLE
Django help-text issue

### ISSUE THREAD

**Issue by akshayprakash2712** [theatlantic/django-nested-admin#246]
I have created a model  field called Company name and i give a helptext on that field. But i want to show the heltext by hovering the field only, otherwise it shows empty. How is it possible ? I will share the screenshot below.
![Screenshot 2024-04-08 202241](https://github.com/theatlantic/django-nested-admin/assets/138870643/ce577eb7-50de-44bc-bd1f-28f50b0d2db2)
![Screenshot 2024-04-08 202300](https://github.com/theatlantic/django-nested-admin/assets/138870643/d2873d9a-c6b0-46f4-987f-47fa305cd44a)
Now it shows under the field but how to change by hovering the field only that will show.

**Comment by fdintino** [comment]
This repository is for django-nested-admin, which allows nesting of inline admins inside other inline admins. I can't really help with general django support questions. Stackoverflow or a django support forum would be better places to pose your question.
