### ISSUE TITLE
Add item does not show form

### ISSUE THREAD

**Issue by philippeluickx** [theatlantic/django-nested-admin#25]
I have a nested inline and the links to add new items do nothing. True for both the parent and the child. Also weird is that I see twice the + graphic as so:

```
+ Add child
 +

+ Add parent
 +
```

**Comment by philippeluickx** [comment]
Also different with other "add item" links is that for the nested inlines, it uses javascript:// while the ones that work (the non-nested inlines) use javascript:void(0)

**Comment by philippeluickx** [comment]
Well, seems this was a mess up on my side in terms of versions. Having another issue though, opening new ticket.

**Comment by jaswanthm** [comment]
Sorry, I have the same issue. May I know how you fixed this ? Thanks!
