### ISSUE TITLE
Session Timeout  on User side

### ISSUE THREAD

**Issue by rahul-5711** [theatlantic/django-nested-admin#250]
Hi all,
I am trying add a session timeout in my Django project by using Django's in-built session middleware. I have implemented session timeout on my project using the Views method I have come across for this purpose and it is working on my Admin side, but in my User side, the redirection that I given not working (i.e. I need to log out the user and get back to the signin page after session expires).

My django version : 5.0.2
My python version: 3.12.2

Now it is taking the time and that page will expire but it will not redirect to the signin page. How can I solve this issue?

What are some other approaches we can use for implementing Sessions on Admin & User sides both redirecting to the Signup page and persisting the last page worked on upon logging back in ?

Settings.py
![middile](https://github.com/theatlantic/django-nested-admin/assets/120029777/96f637b1-e11e-44c4-9e39-de621d65a90e)
![settings](https://github.com/theatlantic/django-nested-admin/assets/120029777/54b6594b-5431-4bef-b9ce-83c73c28037a)

Views.py
![views](https://github.com/theatlantic/django-nested-admin/assets/120029777/814c056f-06b7-483d-994c-4af67d53b718)

urls.py
![url](https://github.com/theatlantic/django-nested-admin/assets/120029777/97c6b5d4-4c36-4837-8c5d-8aa21e7812ed)

**Comment by fdintino** [comment]
This repository is for django-nested-admin, which adds the ability to nest inline admins inside other inline admins. This issue sounds like a general django support question...I would suggest posing it on stackoverflow or in some other support forum.

**Comment by rahul-5711** [comment]
> This repository is for django-nested-admin, which adds the ability to nest inline admins inside other inline admins. This issue sounds like a general django support question...I would suggest posing it on stackoverflow or in some other support forum.

Thankyou for the reply
