### ISSUE TITLE
Issue with Toggling between New Themes

### ISSUE THREAD

**Issue by akshayprakash2712** [theatlantic/django-nested-admin#251]
Hello all,

I'm encountering an issue with a custom Theme Installation in my Django project using v. 4.2.13 and Python v. 3.9.7. In the default Admin side, there is a Moon icon for toggling the Themes (i.e. b/w Light and Dark and Auto). I want to add a Grey theme as my default with a new icon. So there are total 4 icons for themes now - Grey, Light , Dark & Auto. For implementing this, I added a new icon for the Grey theme and the icon is now not visible in the Admin panel (only the default 3 are shown) and the toggling between themes is not working. Below are the screenshots of the code for installing themes with their respective icons.

Please also note my teammate has been working on Django 5.0 for making his previous project commits in Github. We wanted to test what can happen to the same functionality if team members work on different versions since we're assuming Git essentially stores all files as basic text files with version control. I am not sure if this has anything to do with my problem.

Kindly help.

1. Screenshot 1 - The Admin panel moon icon for theme toggle
![Screenshot 2024-06-14 154820](https://github.com/theatlantic/django-nested-admin/assets/138870643/a36b046d-d2d1-4960-85a7-44e1d1c50e95)

2.Screenshot 2 - js file for toggle and add the icon (admin_script.js)
![Screenshot 2024-06-14 155126](https://github.com/theatlantic/django-nested-admin/assets/138870643/981da6e3-b84f-46c7-a98c-fc777b68a757)
![Screenshot 2024-06-14 155139](https://github.com/theatlantic/django-nested-admin/assets/138870643/32c80529-652e-4a91-9019-7e519bd224e8)

3.Screenshot 3 - code for add new toggle icon (color_theme_toggle.html
![Screenshot 2024-06-14 155217](https://github.com/theatlantic/django-nested-admin/assets/138870643/b0c4ad93-91d3-4b57-a8e0-df72ebcd21c6)

4.Screenshot 4 - Add svg file for new icon(new.svg)
![Screenshot 2024-06-14 160849](https://github.com/theatlantic/django-nested-admin/assets/138870643/28f23d0d-02af-4e83-a46e-65613ed925f7)

**Comment by fdintino** [comment]
I think you might have this repository confused for the django project; this is merely an admin add-on for django. Also, github issues are generally for bug reports. You might have better luck on stackoverflow or on a general django support message board.
