### ISSUE TITLE
UI regression with version 4.1.0

### ISSUE THREAD

**Issue by martinlehoux** [theatlantic/django-nested-admin#258]
Hi! Just updated to version 4.1.0 which fixes issue I had with autocomplete and selects.

I think there is a regression in displaying `NestedTabularInline` (I don't see the regression with `NestedStackedInline`). The version on the left if running v4.1.0 while the right one is running v4.0.2
![image](https://github.com/user-attachments/assets/54350161-22c4-41b1-9c1d-ae4cf339e5f7)

**Comment by fdintino** [comment]
I believe this is fixed in the 4.1.1 release.
