### ISSUE TITLE
Deleting child not working

### ISSUE THREAD

**Issue by philippeluickx** [theatlantic/django-nested-admin#26]
When I click the delete link of a child, this checks the parents checkbox for delete... If I click the checkbox of the child delete link, it checks and immediatly unchecks the checkbox of the parent.

Basically impossible to delete a child at the moment?

**Comment by fdintino** [comment]
What version of Django? With or without grappelli? Stacked inlines or tabular inlines?

**Comment by philippeluickx** [comment]
django 1.9.2
without grappelli
stacked inlines

**Comment by philippeluickx** [comment]
By the way, I tried 3 different libs for nested inlines and if you manage to fix this issue, this lib is the only that actually functions completely...

**Comment by fdintino** [comment]
Hmm, I'm not able to replicate this bug. There's even a [unit test](https://github.com/theatlantic/django-nested-admin/blob/d1b16f9dc225b1a96775ed961196d19412c6b1c4/nested_admin/tests/test_admin.py#L532-L556) specifically testing for this functionality and it doesn't fail under the conditions you have. Is it possible there is some other javascript file (or inline javascript) that has a registered click handler on the delete checkboxes? Or are the nested admin javascript files somehow getting included twice?

**Comment by philippeluickx** [comment]
I ran the tests in the same virtualenv and all passed (although 4 were skipped). I'll digg a bit and let you know if I find antyhing else.

Not sure if relevant but the actual graphics look also a bit messed up...

![nested_django](https://cloud.githubusercontent.com/assets/836866/13295983/0b4b8122-db34-11e5-9982-12e2b3b82175.png)

**Comment by philippeluickx** [comment]
Just throwing some observations, might not be relevant...


It seems that when I click on either the child or parent delete checkbox, this line: https://github.com/theatlantic/django-nested-admin/blob/master/nested_admin/static/nesting/nesting.formset.js#L83

will in both cases create a var pointer to the parent checkbox.

When you dive into the $form.djangoFormPrefix() function, it will return just the prefix of the parent, not the children.
Am I missing something?

**Comment by philippeluickx** [comment]
I cleaned up my pip installations, so that this is the only library that messes with the admin pages. Still the same issue, so I don't think I have interference from other packages.

I'll try and set up a basic example in my project to see if that works.

**Comment by philippeluickx** [comment]
Seems to work fine in an example project... Funky. I keep looking.

**Comment by philippeluickx** [comment]
Allright, I found the culprit.

The issue is caused by a **related_name** I use in my child object (models.py). Removing that fixed everything.

I think I can manage to refactor for not using related_name, but still consider this a bug.

**Comment by fdintino** [comment]
What was the `related_name`? In general `related_name` should work (I use it, in fact, in the unit tests). Was the `related_name` the same as the parent model? I could see that causing problems, it does assume that the names of the different levels of the root and inlines are unique. Or was it `+`? I'm not entirely sure what would happen in that case.

**Comment by philippeluickx** [comment]
The related_name was the name of the object +s (so parent object would be "item" then related_name="items")

**Comment by fdintino** [comment]
okay, thanks. I think the issue is that the one is a substring of the other. Shouldn't be too difficult to fix, but I don't think I'll be able to get to it this week.

**Comment by philippeluickx** [comment]
No problem, I refactored back to standard django. Could be problematic though even in that case if the field is named the same as the model (which often makes sense).

Looking forward to the fix and thanks for a great lib!

**Comment by fdintino** [comment]
I've made a few changes to the way that the code deals with form prefixes. Could you check whether this issue still exists?

**Comment by philippeluickx** [comment]
Seems to work now, nice!

**Comment by n3rio** [comment]
I'm not this closed, and it's been a while, but i have this issue except i'm using Django 2 and Grappelli:
- Grappelli:  git+https://github.com/fermorltd/grappelli-safe.git@2.2-compat
- Django: django==2.2.9
The issue is practically the same, i can not delete a child inside an inline, but if a change it to `admin.StackedInline` it works, but of course, this last one won't work as a nested inline.
