### ISSUE TITLE
Javascript CPU usage and memory leak

### ISSUE THREAD

**Issue by irelandscape** [theatlantic/django-nested-admin#262]
It seems like there may be some kind of memory leak linked to a javascript timer constantly expiring and being restarted.
I use Django 3.2.8 with grapelli 4.0.1 and django-nested-admin 4.0.2

I noticed that when my browser is on an object edit page (page is fully loaded), collapsing/expanding nested inline sections result in the page seemingly locking for several seconds. In other words, I can't click anything on the page, the cursor doesn't change while hovering over buttons, tick boxes, etc.

Using the chrome task manager it looks like the browser tab is constantly using ~5% CPU and memory footprint keeps going up, maybe around 1MB per minute.

I used the developer tools and when breaking the javascript code I constantly end up in utils.js on the following line:
```
      return setTimeout(() => patchDjangoFunction(callCount++), 12);
```

I then profiled the code for a few seconds and I attach the resulting screenshot.
![profile_screenshot](https://github.com/user-attachments/assets/7ed71b85-f53f-46ed-8139-26e05e692166)

Thanks for your help.

**Comment by irelandscape** [comment]
Thanks, that was really quick.
When do you think this fix could be in a new release and made available through pip?

**Comment by fdintino** [comment]
It should be in the 4.1.1 release.
