### ISSUE TITLE
Make draggable optional

### ISSUE THREAD

**Issue by philippeluickx** [theatlantic/django-nested-admin#27]
I don't really need the drag and drop ability. Could this be disabled somehow?

**Comment by fdintino** [comment]
If you don't specify a `sortable_field_name` on the inline model admin the drag and drop shouldn't work. Is the issue that the drag handles are still showing up? Or is it still allowing you to drag and drop even without a `sortable_field_name`?

**Comment by philippeluickx** [comment]
I am actually able to drag and drop the divs. No effect on save, so I would argue minor issue.

**Comment by fdintino** [comment]
Hmm, okay, thanks for the report. I'll look into it.

**Comment by philippeluickx** [comment]
Thanks! Also kudos for the fast reply.

**Comment by fdintino** [comment]
Try adding this to the class that extends `NestedStackedInline`:

```
class NoSortStackedInline(NestedStackedInline):
    # ...
    sortable_options = {
        'disabled': True,
    }
```

Adding that dict to the class should disable drag and drop. Seems like something I should add to the documentation.

**Comment by philippeluickx** [comment]
That did it, thanks!
