### ISSUE TITLE
cropduster selectors?

### ISSUE THREAD

**Issue by philippeluickx** [theatlantic/django-nested-admin#29]
Might be some residues from reusing code from another theatlantic project. But I see quite some selectors pointing to cropduster in https://github.com/theatlantic/django-nested-admin/blob/master/nested_admin/static/nesting/nesting.formset.js

Not sure if that has any impact though...

**Comment by fdintino** [comment]
This is not a mistake. Yes, cropduster is another project at The Atlantic, but this is not "reusing code." Cropduster uses inlines and so it needs these lines for compatibility. It's not a bug for the same reason that the grappelli references are not a bug.

**Comment by philippeluickx** [comment]
Allright, thanks for clarifying that!
