### ISSUE TITLE
Support generic relations in admin

### ISSUE THREAD

**Issue by gfairchild** [theatlantic/django-nested-admin#30]
It would be great if this project supported [generic relations in admin](https://docs.djangoproject.com/en/1.9/ref/contrib/contenttypes/#generic-relations-in-admin). Notably, it should support:

* `GenericInlineModelAdmin`
* `GenericTabularInline`
* `GenericStackedInline`

**Comment by fdintino** [comment]
This feature will be added in the 3.0 release. I intend to do some work refactoring the javascript before I make that release, but if this feature is important for you right now you can use the [3.x branch](https://github.com/theatlantic/django-nested-admin/tree/3.x), which also has fairly good test coverage for the new generic inline functionality as well.

One caveat is that, with the 3.0 release, I will be dropping support for Django releases prior to 1.8. Doing so allows me to take advantage of some refactoring that was done in 1.8 that allows me to add the nesting functionality to the admin with much less code.

**Comment by gfairchild** [comment]
That's fantastic news! I don't need it right this second, so I think I'll just hold off now until the release comes out. All my Django projects are running 1.9, so dropping old Django support isn't an issue for me.

**Comment by gfairchild** [comment]
Do you happen to have a rough idea of how much more work will be involved in the 3.x branch before the 3.0 release will happen?

**Comment by fdintino** [comment]
I'm hoping to release either by the end of this week, or at latest sometime next week.

**Comment by gfairchild** [comment]
That's perfect! I recently transitioned a major model in one of my projects to contain a generic relation, so I'll be using this feature right away.

**Comment by gfairchild** [comment]
This is fantastic. I just updated my project, and the generic inlines are working perfectly. Great job!

**Comment by celiao** [comment]
Is it possible to mix `NestedGenericStackedInline` and `NestedStackedInline`?
