### ISSUE TITLE
How does this project differ from django-nested-inline?

### ISSUE THREAD

**Issue by gfairchild** [theatlantic/django-nested-admin#31]
I've been using [django-nested-inline](https://github.com/s-block/django-nested-inline) for quite a while now and just stumbled on this project. It seems as though this project is still actively developed, which has attracted me to it. Is this project a fork of django-nested-inline, or is a completely different implementation? Due to the similarities in the project name, it might be worth devoting a small section of the readme to explaining the differences.

**Comment by fdintino** [comment]
It's a completely different implementation, developed independently of [django-nested-inline](https://github.com/s-block/django-nested-inline), [django-nested-inlines](https://github.com/Soaa-/django-nested-inlines), [dj-nested-inlines](https://github.com/silverfix/dj-nested-inlines), and [django-super-inlines](https://github.com/BertrandBordage/django-super-inlines).

I agree it might be useful to have a part of the README detailing the differences between this implementation and others.

**Comment by gfairchild** [comment]
That would be really useful. I just switched from django-nested-inline to this project, and I'm already a big fan of how the inlines are displayed using indentation. That tiny detail, coupled with the fact that the last commit was only like a week ago has me switched!

**Comment by fdintino** [comment]
I've written docs for this project and included a comparison as you suggested, [available here](http://django-nested-admin.readthedocs.org/en/latest/why_use.html).
