### ISSUE TITLE
DateTime shortcuts don't work when adding another inline

### ISSUE THREAD

**Issue by aiudirog** [theatlantic/django-nested-admin#36]
I already shared this issue in the last one, but because it is a separate issue, I'll add it here.  When adding a new inline, if it has a DateTime field, the shortcuts don't work, instead just jumping you up to the top of the page.  I'm pretty sure this is because adding a new inline essentially copies and pastes the template and then changes the id and name values, but it doesn't re-register the shortcuts to the new ids.

This doesn't seem like a hard fix and it really isn't a huge issue. If you want I can dig into it more and probably find a solution.

**Comment by fdintino** [comment]
Working on this, should have a fix out soon.
