### ISSUE TITLE
Grapelli bug introduced at v2.2.0

### ISSUE THREAD

**Issue by dnkrtz** [theatlantic/django-nested-admin#37]
Using Django 1.9 and Grapelli 2.8.1.

When updating to version >=2.2.0, I can no longer add instances of nested_admin objects (regardless of nesting depth). I click on "add object" but nothing happens. I also noticed a GUI change with this version, not sure if related.

Thanks!

**Comment by fdintino** [comment]
Hmm, we have a tox environment for [that exact setup](https://github.com/theatlantic/django-nested-admin/blob/b629da2c14fe7571330162ba4ece360a18c655ec/tox.ini#L23) (django 1.9 and grappelli 2.8.1) and it passes all of the tests on Travis (and locally, when I run it). Is it possible there aren't some custom css / javascript / templates in your setup, or that a third-party library might be causing the issue. That's not to suggest that whatever it is isn't a bug, but I need a bit more information about your setup to isolate the cause.

**Comment by dnkrtz** [comment]
It works in my local environment (using django dbsqlite3), but not in production, where I use MySQL with the MySQL-python package, could the issue be here?

**Comment by dnkrtz** [comment]
Oh boy, never mind, I forgot to collectstatic -_-
Thanks for the great app!
