### ISSUE TITLE
Decimal values resetting

### ISSUE THREAD

**Issue by cjohns38** [theatlantic/django-nested-admin#39]
I have a simple model of an assessment and an assessment version.  One assessment can have multiple versions.  When I use the nested admin module the version control field is being reset on the UI to incrementing values starting at zero.  I can set the values through the django shell so the model and DB appear to be set up correctly.  I swapped back to the standard django admin and the values were stored and displayed as expected.  Any idea what could be causing the issue? 

DJANGO = 1.8 
django-nested-admin = 3.0.2

```python
# Model
class Assessments(models.Model): 
    """Assessments Table"""
    Assessment = models.CharField(max_length=100, blank=False)
    
    def __unicode__(self):
        return self.Assessment 
    
    class Meta: 
        ordering = ['Assessment']
        verbose_name_plural = "Assessments"
               
class AssessmentVersion(models.Model): 
    """Assessment Versions Table"""
    Assessment = models.ForeignKey('Assessments')
    Version = models.DecimalField(max_digits=4, decimal_places=2)
    Description = models.CharField(max_length=500, blank=True)
    
    def __unicode__(self): 
        return "{0} : {1}".format(self.Assessment, unicode(self.Version))

    class Meta: 
        ordering = ['Assessment','Version']
        verbose_name_plural="Assessment Version"
        

# Admin (swap for standard admin) 
class AssessmentVersionInLine(nested_admin.NestedStackedInline):
    model = AssessmentVersion 
    sortable_field_name = 'Version'
    extra = 0

class AssessmentAdmin(nested_admin.NestedModelAdmin):
    model = Assessments
    fieldsets = [
        (None,               {'fields': ['Assessment']}),
    ]
    sortable_field_name = 'Assessment'
    inlines = [AssessmentVersionInLine]
    extra = 0
```

**Comment by fdintino** [comment]
I think I see what the issue is here. You have `sortable_field_name = 'Version'` in `AssessmentVersionInLine`. The purpose of `sortable_field_name` is to allow for drag-and-drop resorting in the admin. It should point to an `IntegerField` or `PositiveSmallIntegerField` on the model so that it can keep track of the order of the inlines (best practice is to make it a hidden field in the admin). So, upon save (and re-ordering) it will reset all of the `sortable_field_name` fields in the inlines to be their zero-indexed position within the formset.

If you want to allow users to drag-and-drop re-order the inlines, then you should create a separate field, something like:

```python
position = fields.PositiveSmallIntegerField(default=0)
```

Or, if you don't want drag-and-drop sorting, don't include the `sortable_field_name` property on your `InlineAdmin`.

(Side note: `sortable_field_name` doesn't have an effect on `NestedModelAdmin`, only on inlines)

**Comment by cjohns38** [comment]
That was absolutely the issue.  My apologizes for the dumb issue but thank you for the quick response!

**Comment by PatrickRBailey** [comment]
@fdintino Is there a way to change the `sortable_field_name` start value from zero to one? Maybe it could use the default value as the start value? I can't find the javascript where this start value is set.

**Comment by fdintino** [comment]
@PatrickRBailey The line you would need to change is [here](https://github.com/theatlantic/django-nested-admin/blob/24d58a/nested_admin/static/nested_admin/src/nested-admin/sortable.js#L8). See the notes about [contributing](http://django-nested-admin.readthedocs.io/en/latest/contributing.html) in the docs for how to rebuild the javascript.

However, I would advise against making the position field one-indexed. It's possible there are other parts of the code that assume zero-indexing of position, and you're probably better off using `position + 1` anywhere that you need to display it as one-indexed.

**Comment by dacodekid** [comment]
@fdintino would you please explain what you mean by `best practice is to make it a hidden field in the admin`.  I assumed you meant `exclude=('position',)` but that produces a 'KeyError`.

**Comment by fdintino** [comment]
Hi @dacodekid , sorry I wasn't more clear. I didn't mean you should exclude the field (that will cause an error, as you discovered) but that you should render it as a [`HiddenInput`](https://docs.djangoproject.com/en/1.8/ref/forms/widgets/#hiddeninput). There are a few ways to accomplish this. Assuming that you defined the position field on your model as I described above:

```python
position = models.PositiveSmallIntegerField(default=0)
```

then you can use [`ModelAdmin.formfield_overrides`](https://docs.djangoproject.com/en/1.8/ref/contrib/admin/#django.contrib.admin.ModelAdmin.formfield_overrides) to set the widget to `HiddenInput` for `PositiveSmallIntegerField` like so:

```python
from django.db import models
from django import forms
import nested_admin

class AssessmentVersionInline(nested_admin.NestedStackedInline):
    model = AssessmentVersion 
    sortable_field_name = 'position'
    extra = 0
    formfield_overrides = {
        models.PositiveSmallIntegerField: {'widget': forms.HiddenInput},
    }

    class Meta:
        ordering = ['position']
```

This assumes that `position` is the only field on your model that is a `PositiveSmallIntegerField` instance. Another option—slightly more verbose, but perhaps clearer about the intent—is to define a custom `formfield_for_dbfield()` method to make the `position` field hidden:

```python
class AssessmentVersionInline(nested_admin.NestedStackedInline):
    model = AssessmentVersion
    sortable_field_name = 'position'
    extra = 0

    class Meta:
        ordering = ['position']

    def formfield_for_dbfield(self, db_field, request, **kwargs):
        if db_field.name == 'position':
            # Override the position widget to be a HiddenInput
            kwargs['widget'] = forms.HiddenInput()
        return super(AssessmentVersionInline, self).formfield_for_dbfield(
            db_field, request, **kwargs)
```

Hope that helps!

**Comment by dacodekid** [comment]
Awesome 👍 .  In my case, I already have a `Form` for Tabular, so it was

```py
class LineItemForm(forms.ModelForm):
    class Meta:
       ...
        widgets = {
            'position': forms.HiddenInput(),
           ...
        }

```
