### ISSUE TITLE
TinyMCE stacked_inline 

### ISSUE THREAD

**Issue by briang1** [theatlantic/django-nested-admin#47]
There is a known issue with grappelli and TinyMCE when adding another stacked formset. A solution is to override the template as explained in this thread. 
http://stackoverflow.com/questions/5738173/django-grappelli-tabular-inline-add-new-row-tinymce-textfield-not-editable

Is there a solution for this scenario with django-nested-admin?

**Comment by fdintino** [comment]
I don't currently have anything equivalent to Grappelli's `onBeforeAdded` hook, though I could add one if necessary. First I would try using the [`formset:added`](http://django-nested-admin.readthedocs.io/en/latest/customization.html#events) event and see if you can deinitialize and reinitialize the TinyMCE editor with just that. You would add something like the following to a static file in your app that you include with your `class Media` on the admin.

```javascript
(function($) {
    $(document).on('formset:added', function(event, $form) {
        if (window.tinyMCE) {
          deselector = tinyMCE.settings.editor_deselector;
          $form.find('textarea:not(.' + deselector + ')').each(function() {
            var id = $(this).attr('id');
            tinyMCE.execCommand('mceRemoveControl', false, id);
            tinyMCE.execCommand('mceAddControl', false, id);
          });
        }
    })
})(django.jQuery);
```

**Comment by briang1** [comment]
Thanks fdintino. 
Unfortunately the projects require Django LTS (1.8). Django's formset events are new in 1.9.
Would this justify getting onBeforeAdded and onAfterAdded hooks added?

**Comment by fdintino** [comment]
Sorry, the docs are insufficiently clear on that. Those events are a feature of django-nested-admin, even on Django 1.8. The events used to have a different name, but when Django added `formset:added` in 1.9 I renamed them to match.

**Comment by fdintino** [comment]
The relevant code can be found [here](https://github.com/theatlantic/django-nested-admin/blob/027866ced776ed9c336c1aaf011157ef79c62ae0/nested_admin/static/nested_admin/src/nested-admin/jquery.djangoformset.js#L278)

**Comment by briang1** [comment]
OK gotcha. I am now successfully using the `formset:added` hook but there is still issue with the broken TinyMCE instance. 
It seems the timing is critical when invoking the `mceRemoveControl` method in keeping it from breaking.

Re-reading the comments on the Stackoverflow thread:
> // New inlines start as a hidden template with class grp-empty-form.
> // This contains a textarea, which TinyMCE converts correctly, but
> // something about the transformation from template to visible 
> // form breaks TinyMCE, so we need to remove it from the template and 
> // then re-add it after the transformation. 

Even when directly calling `tinyMCE.execCommand("mceRemoveControl", false,  id);` on the added textarea via the js console has no affect in trying to remove the controls if it's an added inline instance.

Can a `before_added` hook be implemented as well?

Btw, thanks for making this available!

**Comment by briang1** [comment]
Hi fdintino, 
Are you still open to throwing in that `onBeforeAdded` hook?
Thanks again!

**Comment by fdintino** [comment]
Hi @briang1  I am, though could you try one last thing first?

In your `tinymce_setup.js` (if you're using the one bundled with grappelli, copy it to a static dir in your project), change `mode` in the `tinyMCE.init()` call to `'none'` and add the following javascript somewhere:

```javascript
(function($) {
    $(document).ready(function() {
        $('.djn-inline-form:not(.grp-empty-form) textarea').each(function() {
            tinyMCE.execCommand("mceAddControl", true, this.id);
        });
    });
})(django.jQuery || window.jQuery);
```

To explain the thinking for the above: I believe the _real_ issue here is that tinymce is registering on all textareas indiscriminately, including those in the "empty forms," which are hidden forms that get cloned to become inlines added via javascript. If you prevent tinymce from adding controls to these textareas in the first place, you shouldn't need to remove them when adding an inline.

**Comment by briang1** [comment]
Hi @fdintino 
Yes the above does work. It first needs to be called on existing formsets (set via inline `extra` property) and also the newly added formsets via `formset:added` mentioned above. 
Adding the `onBeforeAdded` hook would make configuration more consistent with Grappelli... but this does provide a successful work around. 
Thank you for your time on this!

**Comment by an0o0nym** [comment]
Hey @fdintino, 

First of all, thanks for your work with this plugin.

I am trying to use solutions provided in here, but none of those seem to be working.

This is what my `tinymce_setup.js` looks like:

```js
tinymce.init({
  selector: "textarea", // change this value according to your HTML
  mode: "none",
});

(function ($) {
  $(document).ready(function () {
    $(".djn-inline-form:not(.grp-empty-form) textarea").each(function () {
      console.log("init mce", this.id);
      tinyMCE.execCommand("mceAddControl", true, this.id);
    });
  });
})(django.jQuery || window.jQuery);

(function ($) {
  $(document).on("formset:added", function (event, $form) {
    $(".djn-inline-form:not(.grp-empty-form) textarea").each(function () {
      console.log("add new mce", this.id);
      tinyMCE.execCommand("mceAddControl", true, this.id);
    });
  });
})(django.jQuery);
```

 I can see the ids of textareas being logged correctly. however this `execCommand` does not seem to do anything. I also tried calling `tinyMCE.execCommand` with `mceAddEditor` without much success.
 
I also tried solution from OP  StackOverflow URL - also without much success.

Could you give us some hints on how to tackle this issue as it seems to be a problem nowadays still?

**Comment by an0o0nym** [comment]
OK, I figured it out that I did not remove the `selector` from the call to `init`. That was crucial to make it work with the rest of the code snippet unchanged.
