### ISSUE TITLE
TypeError: i is not a constructor

### ISSUE THREAD

**Issue by kamilgregorczyk** [theatlantic/django-nested-admin#49]
I get this error while trying to add new row
I'm using django 1.9.7

**Comment by fdintino** [comment]
I'm going to need more detail than that. [We have extensive test coverage for Django 1.9](https://travis-ci.org/theatlantic/django-nested-admin/jobs/137393620) (86 selenium tests, each running on python 2 and python 3) and they would fail if there were any javascript console errors. At the very least I'll need to see the stack trace and know a bit more about what other third-party admin add-ons you have installed.

**Comment by fdintino** [comment]
Closing this because there is not enough information in the ticket. Please feel free to reopen if you can provide more details.
