### ISSUE TITLE
`sortable_options` AttributeError under Django 1.10

### ISSUE THREAD

**Issue by gfairchild** [theatlantic/django-nested-admin#53]
I just tried upgrading Django to 1.10, and I'm getting the following error: `'EventInlineAdmin' object has no attribute 'sortable_options'`. The traceback ultimately points to:

```
File ".../env/lib/python3.5/site-packages/nested_admin/nested.py" in inline_formset_data
  112.                 'sortableOptions': self.opts.sortable_options,
```

`EventInlineAdmin` is super simple and actually doesn't use this project:

```python
class EventInlineAdmin(admin.TabularInline):
    model = Event
    extra = 0
```

This error is not present with Django 1.9.9.

**Comment by fdintino** [comment]
If your top level admin class extends `nested_admin.NestedAdmin` then all of your inlines will have to extend a `nested_admin` inline subclass, even if they're not using the nested functionality.

**Comment by gfairchild** [comment]
Ah ha! That fixed it. Thanks!

**Comment by animalx123** [comment]
> If your top level admin class extends `nested_admin.NestedAdmin` then all of your inlines will have to extend a `nested_admin` inline subclass, even if they're not using the nested functionality.

its worked for me
