### ISSUE TITLE
"Add link" shown when  options "extra" and "max_num" equal 0

### ISSUE THREAD

**Issue by timur-orudzhov** [theatlantic/django-nested-admin#54]
I've set options for my **NestedTabularInline** like this:

class PackageItemInline(nested_admin.NestedTabularInline):
    model = PackageUnit
    extra = 0
    max_num = 0

But nothing changed, I still see "add link". Could anyone explain what the problem is ?

**Comment by fdintino** [comment]
Could you provide some context? What purpose does an inline with `max_num = 0` serve?

**Comment by timur-orudzhov** [comment]
@fdintino when we set *max_num=0* and *extra=0* for common inlines, "add link" disappear, but for for nested inline it does not work.

**Comment by j2kun** [comment]
I don't know why this was closed, but it is indeed a bug with this project. `max_num = 0` should disable the "add another" button from inlines.

**Comment by fdintino** [comment]
@j2kun it was closed because 02eb051 should fix this issue. Specifically, [this line](https://github.com/theatlantic/django-nested-admin/blob/efb64f4dedb923d6edf849cd4638416f3a2f6c63/nested_admin/static/nested_admin/src/nested-admin/jquery.djangoformset.js#L56) should cause the add another button to be hidden. Is that not the case for you? Could you share the version of Django you are using, whether you are using any django skins such as grappelli or django-suit, and whether you are performing any other customizations on the admin (e.g. other admin enhancement modules, custom `change_form.html` template, etc.)

**Comment by j2kun** [comment]
This is happening for me with a vanilla admin panel for django 1.10. My admin looks roughly like the following, with `FooBatch` foreign-keying to `Foo`, which foreign keys to `FooContainer`.

```
class FooBatchInline(nested_admin.NestedTabularInline):
    model = FooBatch
    fields = ('created', 'batch_size', 'realized_count')
    readonly_fields = fields
    can_delete = False
    max_num = 0
    extra = 0

    def has_add_permission(self, request):
        return False


class FooInline(nested_admin.NestedTabularInline):
    model = Foo
    fields = (...)
    readonly_fields = fields
    can_delete = False
    extra = 0
    max_num = 0
    classes = ('collapse',)
    inlines = [
        ListPurchaseBatchInline,
    ]

class FooContainerAdmin(DjangoObjectActions, nested_admin.NestedModelAdmin):
    model = FooContainer
    ...
    inlines = [FooInline]
```

**Comment by j2kun** [comment]
(the has add permission was a hailmary)

**Comment by fdintino** [comment]
Huh, that's weird. I'm having difficulty reproducing. The following are screenshots from running `tox -e py27-dj110 -- --selenium=chrome TestTabularInlineAdmin.test_add_item_to_empty` ([this selenium test](https://github.com/theatlantic/django-nested-admin/blob/master/nested_admin/tests/two_deep/tests.py#L35-L52)); the first is [TabularItemInline](https://github.com/theatlantic/django-nested-admin/blob/efb64f4dedb923d6edf849cd4638416f3a2f6c63/nested_admin/tests/two_deep/admin.py#L31) without a `max_num` defined, the second with `max_num = 0`:

![TabularItemInline without max_num](https://django-nested-admin-artifacts.s3.amazonaws.com/issues/54-tabular-inline.png)

![TabularItemInline with max_num=0](https://django-nested-admin-artifacts.s3.amazonaws.com/issues/54-tabular-inline-max_num_0.png)

**Comment by j2kun** [comment]
I'll keep looking into it.

**Comment by aventurella** [comment]
Maybe related? I get the add and remove buttons when `max_num = 1` but only when deriving from `nested_admin.*Inline`. If I return to deriving from just `admin.StackedInline`, for example I don't get any buttons (the expected behavior)
