### ISSUE TITLE
Multiplied inlines when ManyToManyField used

### ISSUE THREAD

**Issue by adi-** [theatlantic/django-nested-admin#59]
Models:

```python

class One(models.Model):
    ...

class Two(models.Model):
  one = models.ForeignKey(One)

class Three(models.Model):
  two = models.ForeignKey(Two)
  additional = models.ManyToManyField(SomeModel)
```

Admin:
```python
class OneAdmin():
    inlines = [TwoInline]

class TwoInline(nested_admin.NestedTabularInline):
    model = Two
    extra = 0
    inlines = [ThreeInline]

class ThreeInline(nested_admin.NestedStackedInline):
    model = Three
    extra = 0
```

Having above, I am selecting more than one `additional` in Django Admin. In result, Three model is multiplied by how many rows I have selected in `additional`. Is there any hack for that or it is a bug?

**Comment by adi-** [comment]
More info into that:

`Three` object is not multiplied. It is only showed multiple times in Django Admin.

**Comment by adi-** [comment]
I have figured out what was causing the error: `ordering` in `class Meta`

**Comment by fdintino** [comment]
Yes, I think you may have encountered a known limitation in Django; see the first note in [the docs for `QuerySet.distinct()`](https://docs.djangoproject.com/en/1.10/ref/models/querysets/#django.db.models.query.QuerySet.distinct)

**Comment by adi-** [comment]
Yes, it is probably that one. Is there anything I can do to use distinct() in admin?

Dnia 06.10.2016 o godz. 15:34 Frankie Dintino <notifications@github.com> napisał(a):

**Comment by fdintino** [comment]
It really depends on what specifically you are ordering by. Most likely though you don't actually want to sort by a column on all rows on the related model, but just by the maximum or minimum value of that column. In which case you would do something like:

```python
class SomeModel(models.Model):
	date = models.DateTimeField()

# ...

class ThreeManager(models.Manager):

	def get_queryset(self):
		qset = super(ThreeManager, self).get_queryset()
		return qset.annotate(max_date=models.Max('additional__date'))


class Three(models.Model):
    two = models.ForeignKey(Two)
    additional = models.ManyToManyField(SomeModel)

    objects = ThreeManager()

    class Meta:
        ordering = ('-max_date', )
```

**Comment by adi-** [comment]
Thanx. Closing...
