### ISSUE TITLE
When saving model I get a MultiValueDictKeyError

### ISSUE THREAD

**Issue by javiercf** [theatlantic/django-nested-admin#6]
I have the following code:

    class AnswerNestedInline(NestedStackedInline):
        model = Answer
        extra = 0

    class QuestionInline(NestedStackedInline):
        model = Question
        inlines = [AnswerNestedInline]
        extra = 0

        raw_id_fields = ('media',)
        autocomplete_lookup_fields = {
            'fk': ['media']
        }

    class ActivityAdmin(NestedAdmin):
        inlines = [QuestionInline]
        list_display = ['name','published', 'public', 'created_by']

        def get_readonly_fields(self, request, obj=None):
            readonly = super(ActivityAdmin, self).get_readonly_fields(request, obj)
            if not request.user.has_perm('LMS.publish_activity'):
                readonly += ('published',)
           if not request.user.has_perm('LMS.change_public_status'):
               readonly += ('public',)
           return readonly

When saving the object in the admin I get MultiValueDictKeyError "u'questions-0-id'"

**Comment by fdintino** [comment]
Can you check if you still get the error on the `dev/refactor` branch?

**Comment by javiercf** [comment]
Works with the dev/refactor branch, sorry it took so long for me to reply

**Comment by fdintino** [comment]
FYI, I've since merged the `dev/refactor` branch into master, so you should be good to use that! And thanks for replying.
