### ISSUE TITLE
Nested Inline for a ManyToManyField

### ISSUE THREAD

**Issue by scythargon** [theatlantic/django-nested-admin#61]
I'm getting `'app.Slot' has no ForeignKey to 'app.Intent_task'.` error

```models.py:

class Task(models.Model):
    pass

class Intent(models.Model):
    task = models.ManyToManyField(Task)

class Slot(models.Model):
    intent = models.ForeignKey(Intent)

admin.py:

class TaskAdmin(nested_admin.NestedModelAdmin):
    inlines = [
        IntentInline
    ]

class IntentInline(nested_admin.NestedStackedInline):
    model = Intent.task.through  # see? another model, not Intent itself, and Slot is related exactly to Intent, not to each relation between Intent and Task
    inlines = [
        SlotInline
    ]

class SlotInline(nested_admin.NestedStackedInline):
    model = Slot
```

I see the reason, but can't figure out how to solve it, might be somehow related to get_queryset...

**Comment by fdintino** [comment]
This is actually a limitation of Django inlines, nested or not: it is simply not possible to use a `ManyToManyField` in Django inlines. The last time this came up [I wrote a detailed explanation](https://github.com/theatlantic/django-nested-admin/issues/35#issuecomment-196917418) of why it would not be possible.
