### ISSUE TITLE
Legacy Django support?

### ISSUE THREAD

**Issue by dangayle** [theatlantic/django-nested-admin#62]
What's the earliest version of Django I can find a version of this app for? I'm running a Django 1.5 installation (yes, I know), but would love this functionality. Thoughts?

**Comment by fdintino** [comment]
Compatibility for Django less than 1.8 was dropped with v3.0.0, but the v2.2.6 release should work for Django 1.5.

**Comment by dangayle** [comment]
Awesome. I don't see it in the docs, but can you lay out some super basic models to show what this is connecting? Something like the models listed at the top of [Django Nested Inline's docs](https://github.com/s-block/django-nested-inline)?

```
from django.db import models

class TopLevel(models.Model):
    name = models.CharField(max_length=200)

class LevelOne(models.Model):
    name = models.CharField(max_length=200)
    level = models.ForeignKey('TopLevel')

class LevelTwo(models.Model):
    name = models.CharField(max_length=200)
    level = models.ForeignKey('LevelOne')

class LevelThree(models.Model):
    name = models.CharField(max_length=200)
    level = models.ForeignKey('LevelTwo')
```

**Comment by fdintino** [comment]
That's a good idea. In the meantime if you're looking for examples, the `models.py` and `admin.py` files in `nested_admin.tests` are a good place to start. For instance, the `three_deep` tests are fortuitously more-or-less exactly the same as what you pasted above: [models.py](https://github.com/theatlantic/django-nested-admin/blob/2c71dc41421c1ecbb9e577ceeb1fae97518a1f1e/nested_admin/tests/three_deep/models.py) [admin.py](https://github.com/theatlantic/django-nested-admin/blob/2c71dc41421c1ecbb9e577ceeb1fae97518a1f1e/nested_admin/tests/three_deep/admin.py)

**Comment by fdintino** [comment]
If you don't have any more questions, feel free to close this ticket. Thanks!
