### ISSUE TITLE
Is it possible to mix order of inlines?

### ISSUE THREAD

**Issue by xcono** [theatlantic/django-nested-admin#63]
I have models:
```
# models.py

class ParagraphTable(Paragraph):
    """Paragraph is just a model with GenericForeignKey field"""
    table = TableField()


class ParagraphImages(Paragraph):
    style = models.CharField(default='', max_length=255)


class ImageItem(models.Model):
    file = models.ImageField(upload_to='paragraph/images/%Y/%m/%d')
    parent = models.ForeignKey(ParagraphImages, on_delete=models.CASCADE)


class Node(models.Model):
    title = models.CharField(default='', max_length=255)
```

and admin:

```
# admin.py

class ImageInline(nested.NestedStackedInline):
    model = ImageItem
    extra = 0


class ParagrpaphImagesInline(nested.NestedGenericStackedInline):
    model = ParagrpaphImages
    sortable_field_name = 'order_weight'
    extra = 0
    inlines = [ImageInline]


class ParagraphTableInline(nested.NestedGenericStackedInline):
    model = ParagraphTable
    sortable_field_name = 'order_weight'
    extra = 0


class NodeAdmin(nested.NestedModelAdmin):
    inlines = [ImageStorageInline, ParagraphTableInline]
    weight_field_name = 'order_weight'

```

All works like a charm. Drag and drop support allows me sort my inlines under their parents.
So, I can change sort order between inlines of same type.

But UI allow drag and drop one of inlines under another type. In my case, I can drag ParagraphImages and drop among ParagraphTables. Actually, it is what I really need. But on save I'm getting "MultiValueDictKeyError" or "ManagementForm data is missing or has been tampered with".

Actually, I wrote same app for myself, but I didn't create nested feature and then I found this awesome package. And I solved the problem in a dummy-way, I just reorder back all inlines before save, and reorder on page load.

So, the question: Is it possible to use merged inlines sorted between their types?

===
The purpose of that behaivior is create "polymorphic" content types, there admin can add any inline in any order to build content page (like here: https://www.drupal.org/project/paragraphs)

**Comment by fdintino** [comment]
Interesting. I think it would be difficult, but not impossible. You would want to look at combining the functionality of [how django-polymorphic does inlines](https://github.com/django-polymorphic/django-polymorphic/blob/186f9548b17f82894e249212b277809a465e9702/polymorphic/admin/inlines.py) with how this packages extends django admin functionality. I don't think it will be easy though, I suspect you would have to more-or-less rewrite the javascript in that package, as well as the code in the file I linked to above. But if I were to go about attempting what you want to do, that's where I would start.

**Comment by xcono** [comment]
Thank you Frankie for quick and useful reply, I'll start there.
