### ISSUE TITLE
Suit works and looks OK - unless using tabs

### ISSUE THREAD

**Issue by mQuadrics** [theatlantic/django-nested-admin#64]
Hi.
First of all - this is the first package that works on every django admin system i need - so really thanks for that. But for Django Suit there is a small issue. Suit has a features to use tabs and this does not work with this package.

As it states in documentation http://django-suit.readthedocs.io/en/develop/form_tabs.html#example classes for tabs are defined in property "suit_classes"

Problem is that HTML for nesting/admin/inlines - files stacked.html and tabular.html has no class "suit_classes".

{{ inline_admin_formset.opts.suit_classes }}

First div in Suit stacked
`<div class="inline-group {{ inline_admin_formset.opts.suit_classes }}" id="{{ inline_admin_formset.formset.prefix }}-group">`

First div in django-nested-admin stacked
`<div class="inline-group group djn-group djn-stacked{% if is_nested %} djn-group-nested{% else %} djn-group-root{% endif %}"`

I've seen there are some conditionals "ifsuit", "ifnosuit" in "common" view for standard admin and suit. But for grappelli there are different views. I did not make pull request with a fix because i don't know how you would like to organize this.

I hope my explanation is clear.

**Comment by fdintino** [comment]
@mQuadrics I've pulled in `suit_classes`, can you check on your end if tabs work now?

**Comment by fdintino** [comment]
Closing this as fixed. Please let me know if you run into any issues.
