### ISSUE TITLE
"Add new ..." does not work in 1.10.5

### ISSUE THREAD

**Issue by kamilgregorczyk** [theatlantic/django-nested-admin#67]
I just created a sample, clean project with django 1.10.5 and python 3.5 + django-nested-admin and I see that for both, the NestedStackedInline and the NestedTabularInline "Add new..." stopped working.
<img width="729" alt="zrzut ekranu 2017-02-01 22 56 16" src="https://cloud.githubusercontent.com/assets/9266336/22528040/df4a9200-e8d1-11e6-9c01-2ff5a7803cdd.png">

**Comment by kamilgregorczyk** [comment]
Just tried it on 1.9 and 3.5 and still not working

**Comment by fdintino** [comment]
Why did you close this ticket, is it working now for you? FWIW, I tried to replicate your issue and couldn't, and the tox unit tests do not encounter errors on 1.9 and 1.10. If this is still an issue, could you provide some example code and information about any third-party django apps that might be related, to help troubleshoot? Thanks.

**Comment by vitorcunha1995** [comment]
I am having the same problem.
