### ISSUE TITLE
'module' object has no attribute 'commit_on_success'

### ISSUE THREAD

**Issue by joshglenn** [theatlantic/django-nested-admin#7]
So I'm trying to use the nested admin tool. Upon installation, as soon as I put it in the list of installed apps and put in the URL route, I get the following errors when I try to run the server.

```
/Users/josh/Development/python/tutorial/lib/python2.7/site-packages/django/contrib/admin/util.py:7: RemovedInDjango19Warning: The django.contrib.admin.util module has been renamed. Use django.contrib.admin.utils instead.
  "Use django.contrib.admin.utils instead.", RemovedInDjango19Warning)

/Users/josh/Development/python/tutorial/lib/python2.7/site-packages/nested_admin/formsets.py:6: RemovedInDjango19Warning: django.contrib.contenttypes.generic is deprecated and will be removed in Django 1.9. Its contents have been moved to the fields, forms, and admin submodules of django.contrib.contenttypes.
  from django.contrib.contenttypes.generic import BaseGenericInlineFormSet

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/josh/Development/python/tutorial/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/josh/Development/python/tutorial/lib/python2.7/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/Users/josh/Development/python/tutorial/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/josh/Development/python/tutorial/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/josh/Development/python/tutorial/lib/python2.7/site-packages/django/apps/config.py", line 86, in create
    module = import_module(entry)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/josh/Development/python/tutorial/lib/python2.7/site-packages/nested_admin/__init__.py", line 1, in <module>
    from .options import ModelAdmin, InlineModelAdmin, StackedInline, TabularInline
  File "/Users/josh/Development/python/tutorial/lib/python2.7/site-packages/nested_admin/options.py", line 52, in <module>
    transaction_wrap = getattr(transaction, 'atomic', transaction.commit_on_success)
AttributeError: 'module' object has no attribute 'commit_on_success'
```

Any idea what is going on here?

**Comment by earthboundkid** [comment]
The warnings are because we haven't updated to support Django 1.8 yet. 

I don't understand the final attribute error though. That line says to use `transaction.atomic` (the new-style) where possible and fallback to `transaction.commit_on_success` (the old-style) where necessary. Looking at the Django docs for 1.8, `transaction.atomic` isn't deprecated, so I don't know why your system seems to have neither new nor old-style atomic transactions. If you can figure out what your system is supposed to use for transactions, we'll gladly accept a pull request to add that as well.

**Comment by joshglenn** [comment]
Thanks. I appreciate that. But I'm not sure what information you need from me. I'm very new to Django and relatively new to Python. my Django version is 1.8. Python version 2.7.5 . What do you need me to find out?

**Comment by earthboundkid** [comment]
If you run a Python/Django shell, what happens when you run

```from django.db import transaction
transaction.atomic```

?

**Comment by joshglenn** [comment]
Ok. I did that. This is the response I received:

```
<function atomic at 0x10d028a28>
```

**Comment by earthboundkid** [comment]
I think there must be something else wrong with your setup because you have `django.db.transactions.atomic`, which is what our code expects, but the import is failing anyway, probably for some other unknown reason.

**Comment by earthboundkid** [comment]
Okay, the fix is out now.

**Comment by joshglenn** [comment]
Progress. I am able to build the project now. But when I access the admin page, I get this error:

```
Error during template rendering

In template /Users/josh/Development/python/tutorial/src/django-nested-admin/nested_admin/templates/nesting/admin/inlines/stacked.html, error at line 1
'grp_tags' is not a valid tag library: Template library grp_tags not found, tried django.templatetags.grp_tags,django.contrib.admin.templatetags.grp_tags,django.contrib.staticfiles.templatetags.grp_tags,rest_framework.templatetags.grp_tags,nested_admin.templatetags.grp_tags
1 	{% load i18n grp_tags nested_admin %} 
```

**Comment by fdintino** [comment]
[django-grappelli](https://github.com/sehmaschine/django-grappelli) is a dependency (albeit undocumented at the moment) of django-nested-admin. Because there is not yet a version of grappelli for Django 1.8, we do not currently support Django 1.8. The `dev/refactor` branch of this repository _does_ support Django 1.7 with django-grappelli 2.6.4.

**Comment by joshglenn** [comment]
Ok. Thanks. So I am working on getting that branch installed. Can you look below and see if it installed correctly:

```
pip install -e git+git://github.com/theatlantic/django-nested-admin.git@dev/refactor#egg=django-nested-admin
Obtaining django-nested-admin from git+git://github.com/theatlantic/django-nested-admin.git@dev/refactor#egg=django-nested-admin
  Updating ./src/django-nested-admin clone (to dev/refactor)
Requirement already satisfied (use --upgrade to upgrade): six>=1.7.0 in ./lib/python2.7/site-packages (from django-nested-admin)
Installing collected packages: django-nested-admin
  Running setup.py develop for django-nested-admin
    Creating /Users/josh/Development/python/tutorial/lib/python2.7/site-packages/django-nested-admin.egg-link (link to .)
    Adding django-nested-admin 2.0b2 to easy-install.pth file
    Installed /Users/josh/Development/python/tutorial/src/django-nested-admin
Successfully installed django-nested-admin
```

**Comment by fdintino** [comment]
That looks correct to me!

**Comment by joshglenn** [comment]
Okay. Now I have reached another bump in the road. My app uses UUIDFields as primary keys. That is a function supported by Django 1.8.

```
id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
```

Any idea how can I keep the same functionality using Django 1.7?

**Comment by fdintino** [comment]
Short of waiting until we have added support for Django 1.8, my suggestion is to use the `UUIDField` as a supplementary key and allow Django to manage its own primary key behind the scenes. Something like:

```python
class MyModel(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
```

If that doesn't work for you, you may be able to use [django-extensions](http://django-extensions.readthedocs.org/en/latest/field_extensions.html) to get the functionality you require. I have not worked with it personally, so I'm afraid I can't help you there.

**Comment by fdintino** [comment]
FYI, I've added beta support of Django 1.8 to this project (beta because grappelli has a few outstanding Django 1.8 issues; this code works fine). I'm going to close this issue; if you run into any other problems please open another ticket.
