### ISSUE TITLE
Support show_change_link when using Grapelli

### ISSUE THREAD

**Issue by eagle-r** [theatlantic/django-nested-admin#74]
When using with Grapelli, the `show_change_link` option has no effect in either Tabular or Stacked form.

**Comment by fdintino** [comment]
This isn't a bug with django-nested-admin so much as it's a bug with django-grappelli. In fact, there [has been a ticket open for nearly two years](https://github.com/sehmaschine/django-grappelli/issues/618) to add this functionality. I think it's bizarre that grappelli still does not support `show_change_link`.

**Comment by fdintino** [comment]
This was added to django-grappelli 2.12.2, so we should be able to add this functionality to django-nested-admin now.

**Comment by dgrant** [comment]
@eagle-r @fdintino Anyone get this to work? Doesn't seem to be working for me.

**Comment by fdintino** [comment]
@dgrant this is available in the latest django-nested-admin release.

![grappelli show_change_link screenshot](https://www.frankiedintino.com/static/misc/screenshot-nested-admin-grp-change-link.png)

**Comment by dgrant** [comment]
@fdintino  Wow, thanks!

**Comment by dgrant** [comment]
This still isn't working for me, it's supposed to be used for inlines. The doc says "Specifies whether or not inline objects that can be changed in the admin have a link to the change form." But I don't see any link with my inlines. It does seem to work when I have Grapelli disabled though.

**Comment by fdintino** [comment]
What version of django, django-grappelli, and django-nested-admin are you using?
