### ISSUE TITLE
Not Working with CKeditor

### ISSUE THREAD

**Issue by vladbpython** [theatlantic/django-nested-admin#77]
Whe add new inline not working CKeditor, display only textarea

**Comment by vladbpython** [comment]
Please anyone help, I use https://github.com/django-ckeditor

**Comment by fdintino** [comment]
I am busy right now, but the short answer is that you can hook into the event fired when an inline is added, and initialize the ckeditor widget from there ([docs](http://django-nested-admin.readthedocs.io/en/latest/customization.html#events))

The solution would look vaguely like the following (have not tested):

```javascript
$(document).on('formset:added', function(event, $form, prefix) {
    $form.find('.django-ckeditor-textarea:not([name*="__prefix__"])').ckeditor();
});
```

**Comment by vladbpython** [comment]
working
