### ISSUE TITLE
KeyError while set readonly_fields in second nested inline 

### ISSUE THREAD

**Issue by Arkkienkeli** [theatlantic/django-nested-admin#8]
When I try set readonly fields in second inline, the error comes:
Django Version: 	1.8
Exception Type: 	KeyError
Exception Value: 	u"Key 'second_name' not found in 'SecondForm'"
Exception Location: 	/usr/local/lib/python2.7/dist-packages/django/forms/forms.py in __getitem__, line 167

Here is the code:

    class SecondInLine(nested_admin.NestedStackedInline):
         model = Second
         extra = 1
    #failes
	    def get_readonly_fields(self, request, obj=None):
		   if not request.user.is_superuser and request.user.is_staff:
			    self.readonly_fields = Second._meta.get_all_field_names()
			    return self.readonly_fields
		return self.readonly_fields

    class FirstInline(nested_admin.NestedStackedInline):
	    model = First
	    extra = 1
	    inlines = [
		   SecondInLine,
	    ]

     #works fine
	    def get_readonly_fields(self, request, obj=None):
		    if not request.user.is_superuser and request.user.is_staff:
			   self.readonly_fields = First._meta.get_all_field_names()
			   return self.readonly_fields
		   return self.readonly_fields

    class SomeAdmin(nested_admin.NestedAdmin):
	   inlines = [
		   FirstInline,
	   ]

          #works fine
	    def get_readonly_fields(self, request, obj=None):
		    if not request.user.is_superuser and request.user.is_staff:
			   self.readonly_fields = Some._meta.get_all_field_names()
			   return self.readonly_fields
		    return self.readonly_fields

**Comment by Arkkienkeli** [comment]
Downgraded to django 1.7. No error now, but seems there is bug (I ll leave it as comment here) (when readonly fields for 2nd inline are set, you cant view them) . I ll post code from my project:

	class AimInLine(nested_admin.NestedStackedInline):
		model = Aim
		extra = 1

		def get_readonly_fields(self, request, obj=None):
			if not request.user.is_superuser and request.user.is_staff:
				return self.readonly_fields + ('aim_name','value', 'difference', 'commentary')
			return self.readonly_fields
	
	class KpiInline(nested_admin.NestedStackedInline):
		model = Kpi
		extra = 1
		inlines = [
			AimInLine,
		]
	
		def get_readonly_fields(self, request, obj=None):
			if not request.user.is_superuser and request.user.is_staff:
				return self.readonly_fields + ('name',)
			return self.readonly_fields

	class TermAdmin(nested_admin.NestedAdmin):
		list_filter = ('user',)
		inlines = [
			KpiInline,
		]

		def get_queryset(self, request):
			qs = super(TermAdmin, self).get_queryset(request)
			if request.user.is_superuser:
				return qs
			return qs.filter(user=request.user)
	
		def get_readonly_fields(self, request, obj=None):
			if not request.user.is_superuser and request.user.is_staff:
				return self.readonly_fields + ('user','term','date')
			return self.readonly_fields
	
	admin.site.register(Term, TermAdmin)

**Comment by aiudirog** [comment]
I found the issue and a fix today while trying to create a read-only image preview. I'll be submitting a pull request in a few minutes.

**Comment by aiudirog** [comment]
#33
