### ISSUE TITLE
Adding a blank object while deleting previous one causes error

### ISSUE THREAD

**Issue by jakefb** [theatlantic/django-nested-admin#81]
When I add a new inline object and leave it blank and click the delete button on the previous object I get an error when saving.

Please see the traceback here http://dpaste.com/2SKDDWS

**Comment by fdintino** [comment]
@jakefb that link appears to no longer work. Do you still have the stack trace?

**Comment by fdintino** [comment]
Since it's been over a year without any feedback, I'm closing this issue. Feel free to re-open if you can provide more details.
