### ISSUE TITLE
Frozen item numeration

### ISSUE THREAD

**Issue by artyomnesterenko** [theatlantic/django-nested-admin#82]
When several elements are added, they all have title equal to the forloop.count, but not increasing number, what would be more correctly
![2017-08-02 11-58-36](https://user-images.githubusercontent.com/5736988/28859664-80e01478-777a-11e7-9e0e-71270a73a11d.jpg)
I have django-nested-admin 3.0.19

**Comment by fdintino** [comment]
This will be fixed in 3.0.20. I'll push out a release.

**Comment by fdintino** [comment]
Pull down 3.0.20 and see if it fixes your issue.

**Comment by artyomnesterenko** [comment]
Yes, it works as expected. Thank you!
