### ISSUE TITLE
Incompatible with django-autocomplete-light

### ISSUE THREAD

**Issue by loicteixeira** [theatlantic/django-nested-admin#84]
This package works wonder (thanks) by itself but it does things differently from the default django admin site, it becomes a bit of a pain when paired with [django-autocomplete-light](https://github.com/yourlabs/django-autocomplete-light).

Note that in addition of the issues below, yourlabs/django-autocomplete-light#917 will need to be fixed too in order to achieve full compatibility.

### Issue 1: Inserting the row before renaming the attributes

Django [updates the attributes](https://github.com/django/django/blob/94cd8efc50c717cd00244f4b2233f971a53b205e/django/contrib/admin/static/admin/js/inlines.js#L82) before [inserting the row](https://github.com/django/django/blob/94cd8efc50c717cd00244f4b2233f971a53b205e/django/contrib/admin/static/admin/js/inlines.js#L85) but nested admin [inserts the row](https://github.com/theatlantic/django-nested-admin/blob/fdccdce079fc2f4f48dabf950e6fb9c90d488152/nested_admin/static/nested_admin/src/nested-admin/jquery.djangoformset.js#L245) before [updating the attributes](https://github.com/theatlantic/django-nested-admin/blob/fdccdce079fc2f4f48dabf950e6fb9c90d488152/nested_admin/static/nested_admin/src/nested-admin/jquery.djangoformset.js#L252-L254) which means when initializing an item on [DOMNodeInserted](https://github.com/yourlabs/django-autocomplete-light/blob/622b10757bbd0117c6e4b93e6afc68e124e6b764/src/dal/static/autocomplete_light/autocomplete.init.js#L53-L55), it will fail because not all the element is ready.

FWIW, I don't think it would be possible to initialise on the `formset:added` event because this is supposed to work for regular field for which `formset:added` will never be called.

### Issue 2: Not updating the attributes on all elements

Nested admin only replace the attributes on a [subset of elements](https://github.com/theatlantic/django-nested-admin/blob/1dba49177e32f2fddd35f191cc836bd88114ac49/nested_admin/static/nested_admin/src/nested-admin/utils.js#L22) while Django replace the attributes on [every elements](https://github.com/django/django/blob/94cd8efc50c717cd00244f4b2233f971a53b205e/django/contrib/admin/static/admin/js/inlines.js#L81-L82). However autocomplete light [uses a div](https://github.com/yourlabs/django-autocomplete-light/blob/08d69f0938836d511e1866f77286237c6e4f897b/src/dal/widgets.py#L90-L92) for its field configuration and it doesn't get processed.

**Comment by fdintino** [comment]
Thank you for the detailed issue report! I've pushed out a branch that should address both of the issues you listed in this ticket. Once the autocomplete fixes have been made, I'd also be happy to add integration tests to our test suite.

**Comment by fdintino** [comment]
It sounds like you have a pretty clear idea of what changes need to be made to django-autocomplete-light to resolve the issues. You might get a faster resolution if you forked the repository and opened a pull request with your proposed changes. That would also allow me to verify my fix with an integration test.

**Comment by loicteixeira** [comment]
Thank you for the quick turnaround! I'll try to submit a PR to autocomplete-light next week.

**Comment by dwasyl** [comment]
For what it's worth I've used this with DAL without any issues on a few projects.

**Comment by loicteixeira** [comment]
@dwasyl: Well, it wasn't completely non-functional but trying to use the `forward` feature of `django-autocomplete-light==3.2.10` with `django-nested-admin==3.0.20` did not work.

@fdintino: Again thank you for the quick turnaround. I was hoping the fix to be merged on DAL but it hasn't moved much. For now, you can find it on my fork [loicteixeira/django-autocomplete-light@917-django-nested-admin-compatibility](https://github.com/loicteixeira/django-autocomplete-light/tree/fix/917-django-nested-admin-compatibility).
