### ISSUE TITLE
NestedInline doesn't respect max_num

### ISSUE THREAD

**Issue by arnuschky** [theatlantic/django-nested-admin#87]
When using `StackedInline`, setting `max_num = 1` disabled the "add" link in the top right corner and hides the bottom link "Add another item". When using `NestedStackedInline`, the max_num value isn't respected and the links are always shown.

**Comment by fdintino** [comment]
Could you provide the version of Django you are using, and whether or not you are using Grappelli?

**Comment by arnuschky** [comment]
Sure: 

```
Django==1.8.5
django-grappelli==2.7.2
```

**Comment by corcoran** [comment]
An issue on Django 2.0+ as well.

**Comment by fdintino** [comment]
This was fixed in the 3.0 release.
