### ISSUE TITLE
For end-user readability, provide a setting to change the position index to display starting with 1 instead of 0?

### ISSUE THREAD

**Issue by calcutec** [theatlantic/django-nested-admin#94]
I love having the drag-and-drop functionality along with nested inlines in the admin. Thank you for your work!!

Is there a setting to change the position index for each set of inlines to start with 1?  Or, is there a Javascript callback I could use to display the new position + 1 in another field after drag-and-drop re-positioning functions have completed?

**Comment by elbenfreund** [comment]
I have exactly the same question :)

Thanks for this great packaged, btw.

**Comment by fdintino** [comment]
You could probably write some custom styles for your admin that use [css counters](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Lists_and_Counters/Using_CSS_counters) to show positions
