### ISSUE TITLE
Django 2.0 support?

### ISSUE THREAD

**Issue by fagnerpsantos** [theatlantic/django-nested-admin#95]
When I add it always returns that there are errors to fix, but these errors are not displayed ...

https://uploaddeimagens.com.br/imagens/captura_de_tela_2018-03-27_as_17-51-31-png/mostrar-codigo

**Comment by globophobe** [comment]
I added nested_admin to a new Django 2 project last week. There were no problems. Did you install from pip, or elsewhere?

**Comment by fdintino** [comment]
Is that the standard django 2.0 admin? It looks like you're using some admin add-on that provides tabs. Perhaps the validation error is visible in the other tab?

**Comment by fagnerpsantos** [comment]
I'm using the Django-jet for admin template, and the other tabs not show the any errors.

Changed for default django admin and get the same error:
https://uploaddeimagens.com.br/imagens/screencapture-127-0-0-1-8000-admin-conteudo-curso-add-2018-03-27-19_38_46-png/mostrar-codigo

Thanks for reply :)

**Comment by fagnerpsantos** [comment]
@globophobe I installed it by pycharm and it uses pip

**Comment by fdintino** [comment]
If you replace `nested_admin.NestedModelAdmin` and `nested_admin.NestedStackedInlineAdmin` with the standard django `ModelAdmin` and `StackedInlineAdmin`, load it up without nesting and save, do you still get a validation error?

**Comment by fdintino** [comment]
Oh! Do you maybe have a hidden position field but haven't set `sortable_field_name = 'position'` (or whatever your field is called) in your inline admin class?

**Comment by fagnerpsantos** [comment]
@fdintino If I use the standard django ModelAdmin and StackedInlineAdmin no return errors.
My sortable_field_name for three classes is 'id' and they are hidden fields

**Comment by fagnerpsantos** [comment]
@fdintino Thanks for support. Changing my sortable_field_name to DELETE and it works like magic :)

**Comment by fdintino** [comment]
I could see that going awry and accidentally deleting things. If you don't need them to be sortable then you can just omit `sortable_field_name`. Otherwise it should point to an integer field on the model specifically for sorting

**Comment by fagnerpsantos** [comment]
@fdintino Changes made. Thank you :)
